# Generated by Django 2.1.3 on 2018-12-18 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=400, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('thumbnail', models.CharField(max_length=2000, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=2000, unique=True)),
                ('title', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('thumbnail', models.CharField(default=None, max_length=2000, validators=[django.core.validators.URLValidator()])),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='userprofileinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Video'),
        ),
    ]
