# Generated by Django 2.1.3 on 2018-12-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='userprofileinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification_app.Profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
